### ISSUE TITLE
you wanna know whats sus

### ISSUE THREAD

**Issue by gosoccerboy5** [CluckCluckChicken/Magnifier#18]
THIS
<img width="478" alt="Screen Shot 2021-05-28 at 12 13 47 PM" src="https://user-images.githubusercontent.com/82768218/120019540-33d8e800-bfae-11eb-8123-2848a18f6941.png">
what the heck
why does github think magnifier is mainly CSS :mad: :mad:

**Comment by CluckCluckChicken** [comment]
because of [https://github.com/CluckCluckChicken/Magnifier/blob/main/Spyglass/wwwroot/css/app.css](https://github.com/CluckCluckChicken/Magnifier/blob/main/Spyglass/wwwroot/css/app.css). it contains all of tailwindcss, plus a couple of other classes, and its not minified (in case it measures using line count, although i probably should have it minify at some point). ill probably try and find out how to exclude it from that count, gitignore it and have it github actions generate it with `gulp css`.

**Comment by CluckCluckChicken** [comment]
also [https://github.com/CluckCluckChicken/Magnifier/discussions](https://github.com/CluckCluckChicken/Magnifier/discussions)
