### ISSUE TITLE
Bug: release magnifier

### ISSUE THREAD

**Issue by gosoccerboy5** [CluckCluckChicken/Magnifier#42]
**Describe the bug**

The bug is that it is releasing tomorow

**To Reproduce**

Get all hyped up about this new epic comment reactions and pinning thing, then when you think it will be released it actually doesnt get released

**Expected behavior**

i want it to be released

**Browser Information**

firefox

**Additional context**

ur sus because of this

**Comment by CluckCluckChicken** [comment]
bug fix scheduled for tomorrow

**Comment by JackyBorderCollie** [comment]
yes this is really bug

**Comment by gosoccerboy5** [comment]
It is.. acceptable

**Comment by CluckCluckChicken** [comment]
c# has built in bug fixer (epic gamer) that fixes bugs automatically overnight. u think i actually put time and effort into creating a high quality scratch comment reaction tool? no, i didnt, i just made a lot of bugs then left them all to fix over the last 3 weeks.

the actual reason is because setting up domain stuff

**Comment by JackyBorderCollie** [comment]
imma sleep

**Comment by JackyBorderCollie** [comment]
OMG it's the next day now pleaseeeee release magnifier!!!!

**Comment by FunctionalMetatable** [comment]
Magnifier release today

**Comment by CluckCluckChicken** [comment]
ok i promis i will this time except i just got up to turn off the vm because i forgot last night but fortunately noone tried to use it

**Comment by CluckCluckChicken** [comment]
closed as resolved
