### ISSUE TITLE
new replies arent automatically indexed if theyre already in the database

### ISSUE THREAD

**Issue by CluckCluckChicken** [CluckCluckChicken/Magnifier#9]

**Comment by return-misaPuding** [comment]
Maybe you can pass number of replies while uploading comment so that you
can check how many replies does the already uploaded comment have and
re-upload it if there are new replies?
Also if you will store the number of replies, you can search by it so I
will be able to find a comment with the highest number of replies and hide
in it when the numbers man comes

Dne pá 28. 5. 2021 8:32 uživatel potatophant ***@***.***>
napsal:

**Comment by CluckCluckChicken** [comment]
solved a while ago
